import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./styles/globals.css";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	// title: "Create Next App",
	// description: "Generated by create next app",
	openGraph: {
		title: "",
		description: "",
		images: {
			url: "/icons/metaicon.png", // Must be an absolute URL
			width: 91,
			height: 90,
		},
		url: "",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={font.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
