import type { Metadata } from "next";
import { Cabin } from "next/font/google";

import Navbar from "../components/Navbar";

import "./styles/globals.css";
import styles from "./styles/page.module.css";

const font = Cabin({ subsets: ["latin"] });

export const metadata: Metadata = {
	// title: "Create Next App",
	// description: "Generated by create next app",
	openGraph: {
		title: "",
		description: "",
		images: {
			url: "/icons/metaicon.png", // Must be an absolute URL
			width: 91,
			height: 90,
		},
		url: "",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <div className={styles.children}>{children}</div>;
}
